workflows:
  ios-app-store-release:
    name: Hatipoglu iOS App Store Sürümü
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: latest
      xcode: latest
      cocoapods: default
      groups:
        - AppleKey
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: |
          npm install --ignore-scripts
      - name: Expo Prebuild
        script: |
          npx expo prebuild --platform ios
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build iOS Application
        script: |
          xcode-project build-ipa \
            --workspace ios/*.xcworkspace \
            --configuration Release
    artifacts:
      - ios/build/Build/Products/Release-iphoneos/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
